// Dice.sol constructor arguments. Needed for using 'verify'

const constructorArgs = [

    ["Common","Uncommon","Rare","Mythic","Shiny",
     "Legendary","Bloody","Evil","Pious","Flaming",
     "Dayside","Nightside","Galactic","Freedom",
     "Empirical","Glowing","Charred","Frozen","Broken",
     "Shattered","Bit","Dungeon","Knight","Dragon",
     "Devil","Goblin","Mage","God","Goddess","Royal",
     "Anointed","Exalted","Foretold","Iridescent",
     "Plebian","Patrician","Midnight",
     "Damaged","Perfect","Speedster","Telekinetic",
     "Telepathic","Anodized","Cryogenic","Crystalized","Covalent",
     "Ionic","Oxidized","Wireframe","Ice Forged", "Radioactive",
     "Machined","Unstable","Balanced","Rogue","Pilot",
     "Mother","Father","Baldur","Borr","Bragi","Búri",
     "Dagur","Delling","Eir","Ēostre","Elli","Forseti",
     "Freyja","Freyr","Frigg","Fulla","Gefjun","Hel",
     "Heimdallur","Hermóður","Hlín","Höðr","Hœnir",
     "Iðunn","Jörð","Kvasir","Lofn","Loki","Magni",
     "Máni","Mímir","Nanna","Nerþus","Njörður","Nótt",
     "Óðinn","Sága","Rán","Sif","Sigyn","Sjöfn","Skaði",
     "Snotra","Sol","Thor","Thruer","Týr","Ullr","Váli",
     "Vár","Vé","Víðarr","Vör","Yggdrasil","Wealthy",
     "Regular","Average","Super","Meta","Inhuman","Mutant",
     "Alien","Artisinal","Garbage","Cobbled","Mastercrafted","Silent",
     "Sonic","Sorcerer","Edible","Poisonous","Venomous","Cracked",
     "Infested","Prosperous","Exploding","Accurate",
     "Maiden","Thief","Treasured","Lost","Secret","Deluxe",
     "Salvaged","Restored","Hand-Crafted","Naked","Retrograde",
     "Spawned","Vintage","Assassin","Force","Intelligent", 
     "Chaotic", "Neutral", "Lawful"],

    ["Hydrogen","Helium","Lithium","Beryllium","Boron","Carbon","Nitrogen",
     "Oxygen","Fluorine","Neon","Sodium","Magnesium","Aluminium",
     "Silicon","Phosphorus","Sulfur","Chlorine","Argon","Potassium",
     "Calcium","Scandium","Titanium","Vanadium","Chromium","Manganese",
     "Iron","Cobalt","Nickel","Copper","Zinc","Gallium","Germanium",
     "Arsenic","Selenium","Bromine","Krypton","Rubidium","Strontium",
     "Yttrium","Zirconium","Niobium","Molybdenum","Technetium","Ruthenium",
     "Rhodium","Palladium","Silver","Cadmium","Indium","Tin","Antimony",
     "Tellurium","Iodine","Xenon","Caesium","Barium","Lanthanum","Cerium",
     "Praseodymium","Neodymium","Promethium","Samarium","Europium",
     "Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium",
     "Ytterbium","Lutetium","Hafnium","Tantalum","Tungsten","Rhenium",
     "Osmium","Iridium","Platinum","Gold","Mercury","Thallium","Lead",
     "Bismuth","Polonium","Astatine","Radon","Francium","Radium","Actinium",
     "Thorium","Protactinium","Uranium","Neptunium","Plutonium","Americium",
     "Curium","Berkelium","Californium","Einsteinium","Fermium",
     "Mendelevium","Nobelium","Lawrencium","Rutherfordium","Dubnium",
     "Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium",
     "Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium",
     "Livermorium","Tennessine","Oganesson","Pine","Redwood","Ash","Aspen",
     "Birch","Oak","Fir","Spruce","Cherry","Currant","Mahogany","Wormwood",
     "Aether","Adamite","Bureaucratium","Unobtainium","Dust","Kyber",
     "Netherite","Lapis Lazuli","Meteorite","Obsidian","Suevite","Tektite",
     "Chupacabra","Ogopogo","Snake","Sasquatch","Thunderbird","Yeti",
     "Good","Neutral","Evil"]
];

export default constructorArgs;